spring.application.name=Task-Manager

#Conexion a PostgreSQL

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Crear la base de datos si es necsario
spring.jpa.hibernate.ddl-auto=none
springjpa.show-sql=true